In [15]:
import torch
from torch import nn 
from d2l import torch as d2l
def comp_conv2d(conv2d,X):
    X=X.reshape((1,1)+X.shape)#batch_size and channel_num
    Y=conv2d(X)
    return Y.reshape(Y.shape[2:])
conv2d=nn.Conv2d(1,1,kernel_size=3,padding=1)
X=torch.rand(size=(8,8))
comp_conv2d(conv2d,X)

tensor([[-0.0079, -0.1045, -0.1478, -0.0326, -0.2326, -0.2505, -0.0910, -0.3838],
        [-0.2043, -0.3645,  0.0840,  0.0462, -0.3059, -0.1905,  0.1176, -0.3799],
        [ 0.1384, -0.4623, -0.1903,  0.0924, -0.4855, -0.2756, -0.1443, -0.8590],
        [-0.0513, -0.4110, -0.2176, -0.3126, -0.5061, -0.1524,  0.0805, -0.6047],
        [ 0.0380, -0.3979, -0.0721, -0.0123, -0.5186, -0.1551, -0.2559, -0.7386],
        [ 0.0180, -0.2923, -0.3189, -0.0582, -0.1484,  0.1813, -0.0048, -0.6801],
        [-0.0400, -0.3307, -0.4001, -0.2373, -0.4525, -0.3311, -0.1560, -0.5207],
        [-0.1214, -0.2624, -0.2035,  0.0018, -0.2250, -0.1524, -0.2794, -0.5415]],
       grad_fn=<ViewBackward0>)

In [16]:
conv2d=nn.Conv2d(1,1,kernel_size=3,padding=1,stride=2)
comp_conv2d(conv2d,X)

tensor([[0.2657, 0.3167, 0.5985, 0.3582],
        [0.6464, 0.3270, 0.6966, 0.6961],
        [0.5001, 0.6481, 0.5438, 0.5372],
        [0.3365, 0.4871, 0.4834, 0.3654]], grad_fn=<ViewBackward0>)

# CHANNEL SIZE

I think the channle a little like the HiddenLayer of the MLP
OUTPUT channel:each channel represent a feature of the picture
INPUT channel:means sort or combine then output features

In [21]:
import torch
from d2l import torch as d2l
def corr2d_multi_in(X,K):
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))

In [34]:
X=torch.rand(size=(2,3,3))

In [35]:
X

tensor([[[0.8411, 0.0247, 0.4682],
         [0.6719, 0.1734, 0.6110],
         [0.9198, 0.8384, 0.8566]],

        [[0.6323, 0.3357, 0.2296],
         [0.8847, 0.9491, 0.5970],
         [0.7277, 0.9620, 0.4578]]])

In [41]:
K=torch.rand(size=(2,2,2))
K.shape
K

tensor([[[0.6920, 0.3398],
         [0.7335, 0.6957]],

        [[0.0521, 0.7766],
         [0.3086, 0.6266]]])

In [42]:
corr2d_multi_in(X,K)

tensor([[2.3652, 1.5912],
        [3.3923, 2.6352]])

In [43]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],0)#based on 0_d stack the output
K=torch.stack((K,K+1,K+2),0)
K.shape

torch.Size([3, 2, 2, 2])

In [44]:
corr2d_multi_in_out(X,K)

tensor([[[ 2.3652,  1.5912],
         [ 3.3923,  2.6352]],

        [[ 6.8780,  4.9799],
         [ 9.5192,  8.0804]],

        [[11.3908,  8.3685],
         [15.6461, 13.5255]]])

In [45]:
def corr2d_multi_in_out_11(X,K):
    c_i,h,w=X.shape
    c_o=K.shape[0]
    X=X.reshape((c_i,h*w))
    K=K.reshape((c_o,c_i))
    Y=K@X
    return Y.reshape((c_o,h,w))

In [46]:
X=torch.normal(0,1,(3,3,3))
K=torch.normal(0,1,(2,3,1,1))
Y1=corr2d_multi_in_out_11(X,K)

In [47]:
Y1

tensor([[[ 0.3689,  0.3702,  0.8682],
         [-0.3091, -1.7601, -0.5331],
         [-0.8697, -0.6030,  0.5485]],

        [[-1.9949,  0.8133,  1.9094],
         [ 0.1161,  0.3451, -1.8698],
         [-0.7080, -0.9002,  0.8786]]])