In [1]:
import torch

In [4]:
torch.cuda.is_available()

True

In [5]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3,4)

tensor([[ 1.0381e+00,  6.5674e-01,  8.5841e-01,  1.3398e+00],
        [-4.6390e-01, -3.1476e-01, -3.9944e-01,  2.1046e+00],
        [ 2.1689e+00, -1.5843e-01,  1.6335e-03, -2.0899e+00]])

In [20]:
x=torch.tensor([1.0,2,3,4])
y=torch.tensor([5,6,7,8])
x+y

tensor([ 6.,  8., 10., 12.])

In [22]:
x-y

tensor([-4., -4., -4., -4.])

In [23]:
y/x

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [24]:
x*y

tensor([ 5., 12., 21., 32.])

In [25]:
x**y

tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

In [27]:
x=torch.arange(12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
y=torch.tensor([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
y

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [4, 5, 6, 7]])

In [32]:
torch.cat((x,y),dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 4,  5,  6,  7]])

In [33]:
torch.cat((x,y),dim=1)

tensor([[ 0,  1,  2,  3,  1,  2,  3,  4],
        [ 4,  5,  6,  7,  2,  3,  4,  5],
        [ 8,  9, 10, 11,  4,  5,  6,  7]])

In [34]:
x.sum()

tensor(66)

In [35]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Broadcast Machanism

In [36]:
x=torch.tensor([[1],[2],[3]])
y=torch.tensor([1,2])
x+y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [37]:
x-y

tensor([[ 0, -1],
        [ 1,  0],
        [ 2,  1]])

In [38]:
x*y

tensor([[1, 2],
        [2, 4],
        [3, 6]])

Query Tensor

In [39]:
X=torch.arange(12).reshape(3,4)

In [40]:
X[0]

tensor([0, 1, 2, 3])

In [41]:
X[1:-1]

tensor([[4, 5, 6, 7]])

In [42]:
X[1,1]=9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  9,  6,  7],
        [ 8,  9, 10, 11]])

Save the memory(Pointer)

In [43]:
Y=torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [44]:
before=id(Y)
Y+=X
id(Y)==before

True

In [45]:
Y=Y+X
id(Y)==before

False