In [1]:
import torch

In [5]:
x=torch.arange(4.0)

In [6]:
x

tensor([0., 1., 2., 3.])

In [7]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [8]:
x.grad

In [9]:
y=2*torch.dot(x,x)

In [10]:
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
y.backward()

In [12]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [13]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [14]:
y=x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [15]:
y=x*x

In [16]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [17]:
y.sum().backward()

In [18]:
x.grad

tensor([0., 2., 4., 6.])